### ISSUE TITLE
chcmodel.py with example files

### ISSUE THREAD

**Issue by ndreuu** [chc-comp/chc-tools#15]
I need in `chc_is_refute`. For the beginning, I tried to run `chcmodel.py`: 
` /venv/bin/python chctools/chcmodel.py -m ./example/add_by_one_model.smt2 ./example/add_by_one.smt2`

But as result I got:

> Traceback (most recent call last):
>   File "/home/andrew/PycharmProjects/chc-tools-3/chctools/chcmodel.py", line 102, in <module>
>     sys.exit(cmd.main(sys.argv[1:]))
>   File "/home/andrew/PycharmProjects/chc-tools-3/chctools/core.py", line 95, in main
>     return self.run (args, extra)
>   File "/home/andrew/PycharmProjects/chc-tools-3/chctools/chcmodel.py", line 96, in run
>     res = validator.validate()
>   File "/home/andrew/PycharmProjects/chc-tools-3/chctools/chcmodel.py", line 74, in validate
>     v = self._validate_rule(r)
>   File "/home/andrew/PycharmProjects/chc-tools-3/chctools/chcmodel.py", line 54, in _validate_rule
>     t = self._model.eval(r.head())
>   File "/home/andrew/PycharmProjects/chc-tools-3/chctools/horndb.py", line 431, in eval
>     fn = self.get_fn(term.decl().name())
>   File "/home/andrew/PycharmProjects/chc-tools-3/chctools/horndb.py", line 428, in get_fn
>     return self._fn_interps[name]
> KeyError: 'simple!!query'
> 

What I did wrong?

**Comment by agurfinkel** [comment]
`chc_is_refute` does not exists, in part, because there is no format for refutation. I expect that figuring out an acceptable refutation format would not be easy.

Not sure what is wrong with `chcmodel`. It used to work, but I have not used in in some time. I will take a look.

**Comment by agurfinkel** [comment]
fixed by 29aad20

Spacer expects that queries are simple, that is, consists only of a single predicate. If that is not the case, an extra predicate has to be added. This conflicts with model validation.

I've added a flag to not do this transformation by default. The example now works.
